# Generated by Django 4.2.6 on 2023-11-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='')),
                ('badge_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('service_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('murder', 'murder'), ('kidnapping', 'kidnapping'), ('damaging property', 'damaging property'), ('rape', 'rape'), ('physical or mental abuse', 'physical or mental abuse'), ('theft', 'theft'), ('others', 'others')], max_length=50)),
                ('case', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('completed_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=50)),
                ('culprit', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=50)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops_app.police')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops_app.my_user')),
            ],
        ),
    ]
