# Generated by Django 4.2.6 on 2023-11-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='police',
        ),
        migrations.RemoveField(
            model_name='case',
            name='user',
        ),
    ]
