# Generated by Django 4.2.6 on 2023-11-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0002_remove_case_case_remove_case_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='pic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_user',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
