# Generated by Django 4.2.6 on 2023-12-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entry',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
