# Generated by Django 4.2.6 on 2023-12-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0003_customuser_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entry',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
