# Generated by Django 4.2.6 on 2023-11-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0003_my_user_pic_alter_my_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('m', 'murder'), ('k', 'kidnapping'), ('d', 'damaging property'), ('r', 'rape'), ('p', 'physical or mental abuse'), ('t', 'theft'), ('o', 'others')], max_length=50),
        ),
    ]
