# Generated by Django 4.2.6 on 2023-10-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
