# Generated by Django 4.2.6 on 2023-12-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0004_alter_customuser_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
