# Generated by Django 4.2.6 on 2023-11-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cops_app', '0004_alter_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cops_app.my_user'),
            preserve_default=False,
        ),
    ]
